on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - run: npm install
      - run: tsc
      - run: npm start