on: push
jobs:
  build-node:
    runs-on: ubuntu-lastest
    steps:
      - run: node --version
      - run: npm --version 
      - uses: action/checkout@v4
      - run: npm install
      - run: tsc
      - run: npm start